/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jfx.shapeengine;

import org.junit.Test;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
